### ISSUE TITLE
You should post this in the inventables forum.

### ISSUE THREAD

**Issue by rmasci** [joushou/gocnc#11]
Hi -- You should post this along with precompiled binaries for Windows in the Inventables forum. People are always looking for a better way to send code to their X-Carve (upgrade from Shapeoko 2).  Might give your code more of an install base.  I also code in Go, but don't have my machine built yet but am very glad someone wrote a gcode sender in Go.

Thanks,

Rich

**Comment by joushou** [comment]
Hi Rich!

Glad you like the project. I'm not particularly looking for a large user group - I'm just sharing what I have.

As for the project being Go - that is primarily interesting if you want to play with its internals. Otherwise, you shouldn't really let that be an important factor. As long as you can install it without annoying dependencies (Like, idk, JRE or Node. *shivers*). The project isn't going to be better g-code sender because it's Go, though.

If you want a fancier g-code sender (The main purpose of gocnc was to clean up bad and grbl incompatible gcode, back when MakerCAM and early versions of Easel was the norm), have a look at ChiliPeppr. The actual sender in that project is also Go, in case you want to look at code.

Regards,

Kenny
